geogame/main/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required

from geogame.main.views import (
    RoundView, RoundRecapView, GameRecapView, NewGameView, ChallengeListView,
    EditChallengeView, RemoveCoordView, CoordDeleteView, ChallengeCreateView
)


urlpatterns = [
    url(r'^new-game/$', NewGameView.as_view(), name="new-game"),
    url(r'^round/(?P<game_pk>\d+)/(?P<round_pk>\d+)/$', RoundView.as_view(), name="round-view"),
    url(r'^round-recap/(?P<game_pk>\d+)/(?P<round_pk>\d+)/$', RoundRecapView.as_view(), name="round-recap-view"),
    url(r'^remove-coord/(?P<game_pk>\d+)/(?P<round_pk>\d+)/$', RemoveCoordView.as_view(), name="remove-coord"),
    url(r'^end-recap/(?P<game_pk>\d+)/$', GameRecapView.as_view(), name="end-recap-view"),
    url(r'^create-challenge/$', ChallengeCreateView.as_view(), name="create-challenge"),
    url(r'^list-challenge/$', ChallengeListView.as_view(), name="list-challenge"),
    url(r'^edit-challenge/(?P<pk>\d+)/$', EditChallengeView.as_view(), name="edit-challenge"),
    url(r'^coord/(?P<pk>\d+)/delete/$', CoordDeleteView.as_view(), name="coord-delete"),
]

geogame/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import reverse_lazy

from geogame.main.views import HomePageView, ProfilePageView, UpdateAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    url(r'play/', include(('geogame.main.urls', 'game'), namespace="game")),
    url(r'profile/$', ProfilePageView.as_view(), name="profile"),
    url(r'api-form/(?P<pk>\d+)/$', UpdateAPIView.as_view(), name="api-key-view"),
    url(r'', HomePageView.as_view(), name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geogame/main/models.py
import os
import random
import uuid
import math

from django.contrib.postgres.search import SearchVectorField, SearchQuery, SearchVector
from django.conf import settings
from django.db import models, transaction, IntegrityError
from django.db.models import Avg
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

from geopy import distance


class User(AbstractUser):
    first_name = models.CharField(_('first name'), max_length=50, blank=True, db_index=True)
    last_name = models.CharField(_('last name'), max_length=50, blank=True, db_index=True)
    email = models.EmailField(_('email address'), blank=False, null=False, db_index=True)
    api_key = models.CharField(_('google maps api key'), max_length=255, blank=True, db_index=True)
    display_name = models.CharField(_('display name'), max_length=25, blank=True, db_index=True)

    def generate_new_game(self):
        game = Game.objects.create(
            start=timezone.now(),
            user=self,
            score=0,
            active=True,
            )
        qs = Coord.objects.filter(reports=0)
        coords = qs.order_by('?')[:5]
        for i, coord in enumerate(coords):
            round = GameRound.objects.create(
                game=game,
                coord=coord,
                order=i,
            )
            if i == 0:
                round_id = round.id
        return game.id, round_id

    def get_active_game(self):
        return Game.objects.filter(user=self, active=True).last()

    def deactive_games(self):
        return Game.objects.filter(user=self).update(active=False)


class Challenge(models.Model):
    name = models.CharField(_('Challenge Name'), max_length=255, blank=True, db_index=True)
    user = models.ForeignKey(User, models.PROTECT,
                             related_name='challenge_user',
                             null=False, blank=False)

    def setup_challenge(self, user):
        rounds = Coord.objects.filter(challenge=self)
        #setup games with max score
        game = Game.objects.create(
            challenge=self,
            start=timezone.now(),
            user=user,
            score=0,
            active=True,
        )
        for order, coord in enumerate(rounds):
            round = GameRound.objects.create(
                game=game,
                coord=coord,
                order=order
            )
            if order == 0:
                round_id = round.id
        return game.id, round_id

    @property
    def average(self):
        #this should be cached, but with low volumes its fine as is
        if Game.objects.filter(challenge=self):
            return int(round(Game.objects.filter(challenge=self).aggregate(Avg('score')).get('score__avg', 0)))
        else:
            return 0
        
    @property
    def num_rounds(self):
        return Coord.objects.filter(challenge=self).count()
        
    def num_plays(self):
        return Game.objects.filter(challenge=self).count()


class Coord(models.Model):
    lng = models.CharField(_('longitude'), max_length=50, null=False, blank=False)
    lat = models.CharField(_('latitude'), max_length=50, null=False, blank=False)
    user = models.ForeignKey(User, models.PROTECT,
                             related_name='coord_user',
                             null=False, blank=False)
    reports = models.PositiveIntegerField(default=0)
    challenge = models.ForeignKey(Challenge, models.PROTECT,
                                  related_name='coord_challenge',
                                  null=True, blank=True)

    def report(self):
        self.reports = self.reports + 1
        self.save()


class Game(models.Model):
    challenge = models.ForeignKey(Challenge, models.PROTECT,
                             related_name='game_challenge',
                             null=True, blank=True)
    start = models.DateTimeField()
    user = models.ForeignKey(User, models.PROTECT,
                             related_name='game_user',
                             null=False, blank=False)
    score = models.PositiveIntegerField()
    active = models.BooleanField()

    def get_rounds(self):
        return GameRound.objects.filter(game=self)


class GameRound(models.Model):
    game = models.ForeignKey(Game, models.PROTECT,
                             related_name='round_game',
                             null=False, blank=False)
    coord = models.ForeignKey(Coord, models.CASCADE,
                              related_name='round_coord',
                              null=False, blank=False)
    order = models.IntegerField(_('round order'))
    guess_lat = models.CharField(_('latitude'), max_length=50, blank=True, null=True)
    guess_lng = models.CharField(_('longitude'), max_length=50, blank=True, null=True)
    result = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.guess_lat or not self.guess_lng:
            self.result = 0
        else:
            actual_coord = (self.coord.lat, self.coord.lng,)
            guess_coord = (self.guess_lat, self.guess_lng,)
            #get distance in meters between actual coord and the guess
            dst = distance.distance(actual_coord, guess_coord).km * 1000
            #calculate a score of 0 to 100
            if dst < 100:
                self.result = 100
            elif dst > 100000:
                self.result = 0
            else:
                self.result = int(round(14.46 * (11.52 - math.log(dst))))
        super().save(*args, **kwargs)

geogame/main/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView, ListView
from django.db.models import Avg
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from braces import views

from geogame.main.models import (
    Game, GameRound, Coord, User, Challenge
)
from dal import autocomplete
from geogame.main.forms import GuessForm, ChallengeCoordFormSet, APIForm, ChallengeForm



class HomePageView(TemplateView):
    template_name = 'main/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            if user.api_key:
                context['has_api_key'] = True
                try:
                    game = Game.objects.filter(user=user, active=True)
                    if game and game.exists():
                        game = game.first()
                        if not GameRound.objects.get(game=game, order=4).guess_lat:
                            context['existing_game'] = game
                            rounds = GameRound.objects.filter(game=game).order_by('order')
                            for round in rounds:
                                if not round.guess_lat or not round.guess_lng:
                                    context['existing_round'] = round
                                    break
                except:
                    pass
            else:
                context['has_api_key'] = False
        return context


class ProfilePageView(views.LoginRequiredMixin, TemplateView):
    template_name = 'main/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        games = Game.objects.filter(user=user, active=False).order_by('-id')

        paginator = Paginator(games, 10)
        page = self.request.GET.get('played')
        try:
            played_paginator = paginator.page(page)
        except PageNotAnInteger:
            played_paginator = paginator.page(1)
        except EmptyPage:
            played_paginator = paginator.page(paginator.num_pages)
        context['played_is_paginated'] = played_paginator.has_other_pages()
        context['played_paginator'] = played_paginator

        challenges = Challenge.objects.filter(user=user).order_by('-id')
        paginator = Paginator(challenges, 10)
        page = self.request.GET.get('challenges')
        try:
            challenges_paginator = paginator.page(page)
        except PageNotAnInteger:
            challenges_paginator = paginator.page(1)
        except EmptyPage:
            challenges_paginator = paginator.page(paginator.num_pages)
        context['challenges_is_paginated'] = challenges_paginator.has_other_pages()
        context['challenges_paginator'] = challenges_paginator
        return context


class UpdateAPIView(views.UserPassesTestMixin, UpdateView):
    model = User
    form_class = APIForm
    template_name = 'main/api_form.html'
    raise_exception = True

    def test_func(self, user):
        user = get_object_or_404(User, pk=self.kwargs.get('pk', 0))
        return user == self.request.user

    def get_success_url(self):
        return reverse_lazy('profile')


class ChallengeCreateView(views.LoginRequiredMixin, CreateView):
    template_name = 'main/create_challenge_form.html'
    form_class = ChallengeForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        messages.success(self.request, 'Challenge Created Successfully, add some Co-ords')
        return redirect(reverse_lazy('game:edit-challenge', args=(self.object.id,)))


class EditChallengeView(views.UserPassesTestMixin, TemplateView):
    template_name = 'main/edit_challenge_form.html'

    def test_func(self, user):
        challenge = get_object_or_404(Challenge, pk=self.kwargs['pk'])
        return challenge.user == user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        challenge = get_object_or_404(Challenge, pk=self.kwargs['pk'])
        context['challenge'] = challenge
        context['formset'] = ChallengeCoordFormSet(queryset=Coord.objects.none())
        context['coords'] = Coord.objects.filter(challenge=challenge)
        #add form so users can edit the challenge name
        return context

    def post(self, *args, **kwargs):
        challenge = get_object_or_404(Challenge, pk=self.kwargs['pk'])
        formset = ChallengeCoordFormSet(self.request.POST)

        if formset.is_valid():
            for form in formset:
                obj = form.save(commit=False)
                obj.challenge = challenge
                obj.user = self.request.user
                obj.save()
                #XX prevent duplicates
            messages.success(self.request, 'Co-ords Updated Successfully')
            return redirect(reverse_lazy('game:edit-challenge', args=(challenge.id,)))
        messages.error(self.request, 'The form was invalid - something has gone wrong')
        return redirect(reverse_lazy('game:edit-challenge', args=(challenge.id,)))


class CoordDeleteView(views.UserPassesTestMixin, DeleteView):
    model = Coord

    def test_func(self, user):
        coord = self.get_object()
        return coord.user == user

    def get_success_url(self):
        challenge = self.object.challenge
        messages.success(self.request, 'Coord Removed Successfully')
        return reverse_lazy('game:edit-challenge',args=(challenge.id,))


class ChallengeListView(views.LoginRequiredMixin, ListView):
    template_name = 'main/challenge_list.html'
    context_object_name = 'challenges'
    paginate_by = 50

    def get_queryset(self):
        ids = Coord.objects.filter(challenge__isnull=False).\
            order_by().\
            values('challenge').\
            distinct()

        return Challenge.objects.filter(id__in=ids).order_by('id')


class NewGameView(views.LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = self.request.user
        user.deactive_games()
        if request.GET.get('challenge'):
            challenge = get_object_or_404(Challenge, pk=request.GET.get('challenge'))
            game_pk, round_pk = challenge.setup_challenge(user)
        else:
            game_pk, round_pk = user.generate_new_game()

        return redirect(
            reverse_lazy(
                'game:round-view',
                kwargs={
                    'game_pk': game_pk,
                    'round_pk': round_pk,
                    }
                )
            )


class RoundView(views.UserPassesTestMixin, UpdateView):
    model = GameRound
    form_class = GuessForm
    template_name = 'main/round.html'

    def test_func(self, *args, **kwargs):
        return self.request.user == get_object_or_404(Game, pk=self.kwargs.get('game_pk', 0)).user

    def get_object(self):
        round_id = self.kwargs.get('round_pk', 0)
        return get_object_or_404(GameRound, pk=round_id)

    def get(self, *args, **kwargs):
        round_id = self.kwargs.get('round_pk', 0)
        round = get_object_or_404(GameRound, pk=round_id)

        if round.guess_lat:
            # user has already played this round, so something has gone wrong
            messages.warning(self.request, 'You have already played this round, something went wrong. Hit "Continue Last Game" to try again.')
            return redirect(reverse_lazy('home'))

        return super().get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(RoundView, self).get_context_data(**kwargs)
        user = self.request.user
        round_id = self.kwargs.get('round_pk', 0)
        round = get_object_or_404(GameRound, pk=round_id)

        context['api_key'] = user.api_key
        context['lat'] = round.coord.lat
        context['lng'] = round.coord.lng
        context['game_pk'] = round.game.pk
        context['round_pk'] = round.pk
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if not self.object.guess_lat or not self.object.guess_lng:
            self.object.guess_lat = 0
            self.object.guess_lng = 0
        self.object.save()
        #add to the score and save against the game object, makes for easier score retrieval later
        self.object.game.score = self.object.game.score + self.object.result
        self.object.game.save()
        return redirect(
            reverse_lazy(
                'game:round-recap-view',
                kwargs={
                    'game_pk': self.object.game.pk,
                    'round_pk': self.object.pk,
                    }
                )
            )


class RemoveCoordView(View):
    def post(self, request, *args, **kwargs):
        round = get_object_or_404(GameRound, pk=self.kwargs.get('round_pk', 0))
        game = get_object_or_404(Game, pk=self.kwargs.get('game_pk', 0))
        dodgy_coord = round.coord
        dodgy_coord.report()

        if game.challenge:
            round.score = 100
            round.guess_lat = 0
            round.guess_lng = 0
            round.save()
            next = round.order + 1
            next_round = GameRound.objects.filter(
                game=game,
                order=next,
            ).first()
            if next_round:
                return redirect(
                    reverse_lazy(
                        'game:round-view',
                        kwargs={
                            'game_pk': game.pk,
                            'round_pk': next_round.pk,

geogame/templates/main/homepage.html
{% extends 'game_base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <h1 class="section-header">Welcome to Geogame</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      {% if user.is_authenticated %}
        {% if has_api_key %}
          {% if existing_game %}
            <a class="btn btn-info btn-lg btn-block" href="{% url 'game:round-view' game_pk=existing_game.id round_pk=existing_round.id %}" role="button">Continue Last Game</a>
            <a class="btn btn-success btn-lg btn-block" href="{% url 'game:new-game' %}" role="button">New Random Game</a>
            <a class="btn btn-warning btn-lg btn-block" href="{% url 'game:list-challenge' %}" role="button">View Challenges</a>
          {% else %}
            <button type="button" class="btn btn-info btn-lg btn-block" disabled>Continue Last Game</button>
            <a class="btn btn-success btn-lg btn-block" href="{% url 'game:new-game' %}" role="button">New Random Game</a>
            <a class="btn btn-warning btn-lg btn-block" href="{% url 'game:list-challenge' %}" role="button">View Challenges</a>
          {% endif %}
        {% else %}
          <div class="alert alert-warning">
            You must set an api key on your profile page to play the game. Please read the FAQ for more info.
          </div>
          <button type="button" class="btn btn-info btn-lg btn-block" disabled>Continue Last Game</button>
          <button type="button" class="btn btn-success btn-lg btn-block" disabled>New Random Game</button>
          <button type="button" class="btn btn-warning btn-lg btn-block" disabled>View Challenges</button>
        {% endif %}

      {% else %}
        <div class="alert alert-danger">
          You must be logged in to play the game. Please read the FAQ for more info.
        </div>
        <button type="button" class="btn btn-info btn-lg btn-block" disabled>Continue Last Game</button>
        <button type="button" class="btn btn-success btn-lg btn-block" disabled>New Random Game</button>
        <button type="button" class="btn btn-warning btn-lg btn-block" disabled>View Challenges</button>
      {% endif %}
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <h3 class="section-header">FAQ</h3>
      <p><strong>What is this?</strong></p>
      <p>This is a game that uses <a href="http://www.geoguessr.com">Geoguessr</a> as inspiration.</p>
      <p><strong>Why does this exist?</strong></p>
      <p>Sadly, because of Google's predatory pricing strategy for their Maps api, geoguessr have had to modify their game in a detrimental way to cut costs.</p>
      <p>I created this little site to allow people to play the game how it used to be (or as close to it).</p>
      <p><strong>Why do I need an api key?</strong></p>
      <p>To get around the aforementioned api pricing strategy I require you to upload your own api key.</p>
      <p>Your api key will be used only for games that you play, each key has $200/month free usage, which is plenty for all but the most avid players.</p>
      <p><strong>How do I get an api key?</strong></p>
      <p>Go <a href="https://developers.google.com/maps/documentation/javascript/get-api-key">here</a> and register to get an api key.</p>
      <p>Once you have a key save it against your profile <a href="{% url 'profile' %}">here</a>.
      <p><strong>Is this safe?</strong></p>
      <p>All I can do is offer assurances that I won't use the api keys for anything other than their stated purpose: namely, for each individual's games on this site.</p>
      <p>This site uses django's built in authentication framework, and I have taken every care to look after your personal details.</p>
      <p><strong>What does the "Broken Streetview" button do?</strong></p>
      <p>Sometimes a coordinate with no valid streetview is selected for you, you will just get a black screen.</p>
      <p>If this occurs please click the "Broken Streetview" button and you will be provided with a new scene and the faulty coordinate will be removed from the database.</p>
      <p><strong>There isn't a great variety of countries, why?</strong></p>
      <p>I am relying on crowd sourcing of playable scenes, please consider helping out by <a href="{% url 'game:create-challenge' %}">adding a few coordinates of your own</a>.</p>
      <p>You get to keep track of the coordinates you add, and see how well (or badly) other people do on them!</p>
      <p>For now I have managed to find some data on uk coordinates that I can use, but its not so easy getting data for other countries.</p>
      <p><strong>I didn't receive my email reset password, what gives?</strong></p>
      <p>I am using a free mail server to send password reset emails, the limit is 100/day.</p>
      <p>If you require assistance accessing your account, please email edward.wilding3@gmail.com</p>
      <p><strong>This site is amazing, how can I contact you to discuss this, or another, site?</strong></p>
      <p>Thank you! Please get in touch: edward.wilding3@gmail.com</p>

      <h4>Now go out there and have some fun exploring the world!</h4>
    </div>
  </div>
</div>
{% endblock %}

geogame/templates/main/profile.html
{% extends 'game_base.html' %}
{% load humanize %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <h1 class="section-header">Your Profile</h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <p>Logged in as {{user.email}}</p>
      <p>
        <a class="btn btn-primary btn-lg" style="margin-top:16px" href="{% url 'account_change_password' %}">Change Password</a>
      </p>
      <p>
        <a class="btn btn-primary btn-lg" href="{% url 'api-key-view' pk=user.pk %}">Edit Details</a>
      </p>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <h3 class="section-header">Played Games</h3>
      <hr>
      {% if played_paginator %}
        <table>
          <tr>
            <th style="width:70%">Game</th>
            <th style="width:15%">Score</th>
            <th style="width:15%"></th>
          </tr>
          {% for game in played_paginator %}
            <tr>
              <td style="width:60%">
                {% if game.challenge %}{{game.challenge.name}}{% else %}Random Game{% endif %}
              </td>
              <td>
                {{game.score|intcomma}}
              </td>
              <td>
                <a class="btn btn-primary btn-block" href="{% url 'game:end-recap-view' game_pk=game.pk %}">View</a>
              </td>
            </tr>
          {% endfor %}
        </table>
        {% if played_is_paginated %}
          <ul class="pagination">
            {% if played_paginator.has_previous %}
              <li class="page-item"><a class="page-link" href="?played=1&challenges={{challenges_paginator.number}}">First</a></li>
              <li class="page-item"><a class="page-link" href="?played={{ played_paginator.previous_page_number }}&challenges={{challenges_paginator.number}}">{{ played_paginator.previous_page_number }}</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ played_paginator.number }}</a></li>
            {% if played_paginator.has_next %}
              <li class="page-item"><a class="page-link" href="?played={{ played_paginator.next_page_number }}&challenges={{challenges_paginator.number}}">{{ played_paginator.next_page_number }}</a></li>
              <li class="page-item"><a class="page-link" href="?played={{ played_paginator.paginator.num_pages }}&challenges={{challenges_paginator.number}}">Last</a></li>
            {% endif %}
          </ul>
        {% endif %}
      {% else %}
        <p>You haven't played any games yet, what are you waiting for?</p>
      {% endif %}
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 content">
      <h3 class="section-header">Your Contributions</h3>
      <hr>
      {% if challenges_paginator %}
        <table>
          <tr>
            <th style="width:70%">Challenge Name</th>
            <th style="width:15%">Average Score</th>
            <th style="width:15%"></th>
          </tr>
          {% for challenge in challenges_paginator %}
            <tr>
              <td>{{challenge.name}}</td>
              <td>{{challenge.average|intcomma}}</td>
              <td><a class="btn btn-warning btn-block" href="{% url 'game:edit-challenge' pk=challenge.pk %}" role="button">Edit</a></td>
            </tr>
          {% endfor %}
        </table>
        {% if challenges_is_paginated %}
          <ul class="pagination">
            {% if challenges_paginator.has_previous %}
              <li class="page-item"><a class="page-link" href="?challenges=1&played={{played_paginator.number}}">First</a></li>
              <li class="page-item"><a class="page-link" href="?challenges={{ challenges_paginator.previous_page_number }}&played={{played_paginator.number}}">{{ challenges_paginator.previous_page_number }}</a></li>
            {% endif %}
            <li class="page-item active"><a class="page-link" href="#">{{ challenges_paginator.number }}</a></li>
            {% if challenges_paginator.has_next %}
              <li class="page-item"><a class="page-link" href="?challenges={{ challenges_paginator.next_page_number }}&played={{played_paginator.number}}">{{ challenges_paginator.next_page_number }}</a></li>
              <li class="page-item"><a class="page-link" href="?challenges={{ challenges_paginator.paginator.num_pages }}&played={{played_paginator.number}}">Last</a></li>
            {% endif %}
          </ul>
        {% endif %}
      {% else %}
        <p>You haven't added any challenges, try adding one.</p>
      {% endif %}
      <hr>
      <a class="btn btn-primary btn-lg" href="{% url 'game:create-challenge' %}">Create a New Challenge</a>
    </div>
  </div>
</div>

{% endblock %}

geogame/templates/main/round.html
{% extends 'game_base.html' %}

{% block content %}

{% if messages %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            {{ message }}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}


<div id="map" class="map panoramaMap"></div>

<div id="map2" class="map guessMap"></div>

<div class="mapButtons">
  <button id="resizeMap" type="submit" class="btn btn-dark btn-circle btn-xl mapButton" title="Toggle Map">Map</button>
  <button id="returnToStart" type="submit" class="btn btn-info btn-circle btn-xl mapButton" title="Return To Start">Start</button>
  <form class="mapForm" action="{% url 'game:round-view' game_pk=game_pk round_pk=round_pk %}" method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary btn-circle btn-xl mapButton" title="Make Your Guess">Guess</button>
  </form>

  <form class="mapForm" action="{% url 'game:remove-coord' game_pk=game_pk round_pk=round_pk %}" method="POST"  onsubmit="return confirm('Are you sure this streetview is broken?');">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-circle btn-xl mapButton" title="Report Broken Streetview">Broken</button>
  </form>
</div>

<script>
  function initializeMaps() {
    var panorama = new google.maps.StreetViewPanorama(
        document.getElementById('map'), {
          position: {lat: {{lat}}, lng: {{lng}}},
          addressControl: false,
          linksControl: true,
          enableCloseButton: false,
          showRoadLabels: false,
    });

    var myLatLng = {lat: 0, lng: 0};
    var centreLatLng = {lat: 30, lng: 0};

    var map2 = new google.maps.Map(document.getElementById('map2'), {
      zoom: 2,
      center: centreLatLng
    });

    marker = new google.maps.Marker({
      position: myLatLng,
      map: map2,
      title: 'Your Guess',
      draggable:false,
    });

    google.maps.event.addListener(map2, 'click', function(event) {
       placeMarker(event.latLng);
       $("#id_guess_lat").val(event.latLng.lat());
       $("#id_guess_lng").val(event.latLng.lng());
    });

    function placeMarker(location) {
      marker.setMap(null);
      marker = new google.maps.Marker({
        position: location,
        map: map2
      });
    };

    function returnToStart() {
      panorama.setPosition(new google.maps.LatLng({{lat}},{{lng}}));
    };

    document.getElementById("returnToStart").addEventListener("click", function(){
      returnToStart()
    });

    var toggle = false
    document.getElementById("resizeMap").addEventListener("click", function(){
      if (toggle == true) {
        console.log("show it");
        toggle = false;
        document.getElementById('map2').style.minHeight = "40vh";
        document.getElementById('map2').style.height = "40vh";
        document.getElementById('map').style.height = "53vh";
      } else {
        console.log("hide it");
        toggle = true;
        document.getElementById('map2').style.minHeight = "0vh";
        document.getElementById('map2').style.height = "0vh";
        document.getElementById('map').style.height = "93vh";
      };
      google.maps.event.trigger(panorama, 'resize');
    });

  }



</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key={{user.api_key}}&callback=initializeMaps">
</script>

{% endblock %}